### ISSUE TITLE
Dependency

### ISSUE THREAD

**Issue by a7hybnj2** [rocatj12/MacUninstaller#4]
Hey, sorry if I jumped on board to early but I was specifically looking for a utility just like this one. I had been using AppCleaner and I just didn't like how it felt. I will continue to test this out and look forward to a beta or even stable release.

Add this dependency to the readme?
```
~/D/T/MacUninstaller (master) ▶︎︎ sudo python MacUninstaller.py -a Arduino -m 2
Password:
Traceback (most recent call last):
  File "MacUninstaller.py", line 36, in <module>
    from send2trash import send2trash # Due to Python not wanting to behave when working with the trash, using this library to help with it. Docs: https://pypi.org/project/Send2Trash/
ImportError: No module named send2trash
~/D/T/MacUninstaller (master) ▶︎︎ 
```

**Comment by a7hybnj2** [comment]
well I `pip3 install send2trash` and restarted and I still get the same error. I did a `python3` and `help('modules')` and send2trash is in the list.

**Comment by rocatj12** [comment]
Ah, thank you for catching this, it completely slipped my mind after I installed the module on my computer. 

The dependency is no longer being used due to a few issues I'm having with it and it has either been removed or commented out from the code. Was able to run program on computer that did not have the module installed. 

As an aside, because I may include the Send2Trash module in the future, I believe installing the dependency might work using `pip install Send2Trash` due to using Python 2 vs Python 3. I may be wrong about this but that is how I installed it and got it working on my computer previously.
As you suggested, I will be sure to note it in the readme if it is included and required in the future.
